version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: backend/docker/jenkins.Dockerfile
    container_name: wdp301-jenkins
    user: root # Allows Jenkins to run docker commands via socket as root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      # Mounting docker socket to allow Jenkins to build docker images
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - wdp301-network

networks:
  # Connect to the main project's network
  wdp301-network:
    name: wdp301_wdp301-network
    external: true

volumes:
  jenkins_data:
