# Dev environment overrides
global:
  environment: dev
  domain: dev.wdp301.local

frontend:
  replicaCount: 1

gateway:
  env:
    NODE_ENV: "development"
    MONGODB_URI: "mongodb://mongodb-svc:27017/wdp301-dev"
auth:
  env:
    NODE_ENV: "development"
    MONGODB_URI: "mongodb://mongodb-svc:27017/wdp301-dev"
user:
  env:
    NODE_ENV: "development"
    MONGODB_URI: "mongodb://mongodb-svc:27017/wdp301-dev"
inventory:
  env:
    NODE_ENV: "development"
    MONGODB_URI: "mongodb://mongodb-svc:27017/wdp301-dev"
supplier:
  env:
    NODE_ENV: "development"
    MONGODB_URI: "mongodb://mongodb-svc:27017/wdp301-dev"

ingress:
  hosts:
    - host: dev.wdp301.local
      paths:
        - path: /api
          pathType: Prefix
          serviceName: backend-svc
          servicePort: 4000
        - path: /health
          pathType: Prefix
          serviceName: backend-svc
          servicePort: 4000
        - path: /
          pathType: Prefix
          serviceName: frontend-svc
          servicePort: 3000
